apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: zero2k8s
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      
    scrape_configs:
    - job_name: 'prometheus'
      # Scrape Prometheus itself
      static_configs:
      - targets: ['localhost:9090']
      
    - job_name: 'zero2k8s-cop'
      # Use Kubernetes service discovery to find services
      kubernetes_sd_configs:
      - role: service
        # Limit discovery to the 'zero2k8s' namespace
        namespaces:
          names:
          - zero2k8s
          
      # Relabeling rules to select and configure targets
      # --- Start Corrected Section (from prometheus_config_fix_2) ---
      relabel_configs:
      # Keep only services with the 'prometheus.io/scrape: true' annotation
      - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scrape]
        action: keep
        regex: true
      # Use the service name as the job label (optional but good practice)
      - source_labels: [__meta_kubernetes_service_name]
        action: replace
        target_label: job

