apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: prometheus-service-discovery
  namespace: zero2k8s
rules:
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: prometheus-service-discovery-binding
  namespace: zero2k8s
subjects:
- kind: ServiceAccount
  name: default
  namespace: zero2k8s
roleRef:
  kind: Role
  name: prometheus-service-discovery
  apiGroup: rbac.authorization.k8s.io