apiVersion: apps/v1
kind: Deployment
metadata:
  name: zero2k8s-cop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zero2k8s-cop
  template:
    metadata:
      labels:
        app: zero2k8s-cop
    spec:
      containers:
      - name: zero2k8s-cop
        image: metanets/zero2k8s-cop:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000  # Adjust port based on your COP
        resources:
          requests:
            cpu: "0.2"
            memory: "256Mi"
          limits:
            cpu: "0.5"
            memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: zero2k8s-cop-service
spec:
  selector:
    app: zero2k8s-cop  # Properly indented under `spec`
  ports:
  - port: 80
    targetPort: 8000  # Match container port
  type: LoadBalancer

  #yaml/cop-service.yaml