apiVersion: apps/v1
kind: Deployment
metadata:
  name: zero2k8s-cop
  labels:
    app: zero2k8s-cop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zero2k8s-cop
  template:
    metadata:
      labels:
        app: zero2k8s-cop
    spec:
      containers:
      - name: zero2k8s-cop
        image: zero2k8s-cop:latest
        imagePullPolicy: IfNotPresent  # Add this line
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: zero2k8s-cop-service
spec:
  selector:
    app: zero2k8s-cop
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer